### ISSUE TITLE
podman machine init failed

### ISSUE THREAD

**Issue by fanqiehc** [simnalamburt/homebrew-x#3]
`
➜  ~ podman machine init

Downloading VM image: fedora-coreos-34.20210901.dev.0-qemu.aarch64.qcow2.xz: done
Extracting compressed file
Error: exit status 1
`

The VM image is correctly downloaded. Same sha256sum with https://fedorapeople.org/groups/fcos-images/builds/latest/aarch64/meta.json .

`
➜  ~ sha256sum ~/.local/share/containers/podman/machine/qemu/fedora-coreos-34.20210901.dev.0-qemu.aarch64.qcow2.xz
34e36d2d7741fb5aab7bc27b6948bbf185510a32b43271ec8f90ce175617998d  ./.local/share/containers/podman/machine/qemu/fedora-coreos-34.20210901.dev.0-qemu.aarch64.qcow2.xz
`

`
➜  ~ podman machine start

INFO[0000] waiting for clients...
INFO[0000] listening tcp://0.0.0.0:7777
INFO[0000] new connection from  to /var/folders/78/svdq05m94rq29_rt9z6p_n8m0000gn/T/podman/qemu_podman-machine-default.sock
Waiting for VM ...
qemu-system-aarch64: -drive file=/Users/***/.local/share/containers/podman/machine/qemu/podman-machine-default_ovmf_vars.fd,if=pflash,format=raw: Could not open '/Users/***/.local/share/containers/podman/machine/qemu/podman-machine-default_ovmf_vars.fd': No such file or directory
Error: dial unix /var/folders/78/svdq05m94rq29_rt9z6p_n8m0000gn/T/podman/podman-machine-default_ready.sock: connect: connection refused
ERRO[0003] cannot receive packets from , disconnecting: cannot read size from socket: EOF
ERRO[0003] cannot read size from socket: EOF
`

**Comment by simnalamburt** [comment]
It’s weird your podman’s drive file location is quite different from the
default value and I failed to reproduce this issue. May I ask your macOS
version and hardware information?

And I’d like to let you know that if you already have created a podman
machine with the other version of podman, you must delete the machine
before trying out the podman-apple-silicon. Can you try to remove it and
init a VM again?

2021년 9월 6일 (월) 20:44, zhanghc ***@***.***>님이 작성:

**Comment by fanqiehc** [comment]
@simnalamburt Thank you for your reply!
My mac is `MacBook Air (M1, 2020)`. I think I never used podman on this mac before.
I also used `podman machine rm` to remove the VM, but encountered this problem again.
Could you tell me where is the drive file's default location?

**Comment by fanqiehc** [comment]
I find the root of this problem is `dd` command.
I'm using `coreutils` commands installed by homebrew.
The gnu `dd` command does not accept lowercase in `bs`.
The apple `dd` command does not accept uppercase.
And the podman use lowercase in the code.
https://github.com/simnalamburt/podman/blob/main/pkg/machine/qemu/options_darwin_arm64.go#L25

After I remove gnu dd in PATH, the problem is solved.
Thank you again.

**Comment by simnalamburt** [comment]
Wow that was something that I didn’t expect.. Thanks for the dubugging!

2021년 9월 6일 (월) 21:24, zhanghc ***@***.***>님이 작성:
