### ISSUE TITLE
Clock in the VM is not correct

### ISSUE THREAD

**Issue by theomega** [simnalamburt/homebrew-x#8]
After some time of running the podman VM, the time inside the VM is not in sync anymore with the host machine. The difference can be huge, several hours:

```
$ date -u; podman machine ssh date -u;
Tue Sep 14 20:25:53 UTC 2021
Mon Sep 13 04:46:47 UTC 2021
```

This has strange effects, i.e. a container just started is displayed as "created 40 hours ago".

I suggest to add an ntp client inside the VM to keep the time in sync with the reality.

**Comment by simnalamburt** [comment]
I think it's issue of upstream podman
